Numpy Intro

In [1]:
import numpy as np

Arrays

In [2]:
# 1D Array

arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
# 2D Array
ar = np.array([[1, 2, 3], [4, 5, 6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# 3D Array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Shape of Array


In [6]:
# 1D Array = Vector
arr1 = np.array([1,2,3])
arr1
# 2D Array = Matrix
arr2 = np.array([[1,2,3], [4,5,6]])
arr2
# 3D Array = Tensor, Matrix
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
arr3

# get shape of array

arr1.shape # (3,) -> 1 row and 3 columns
arr2.shape # (2, 3) -> 2 rows and 3 columns
arr3.shape # (2, 2, 3) -> 2 matrices, each with 2 rows and 3 columns


(2, 2, 3)

Attributes and Functions on array


In [7]:
# .ndim # get number of dimensions of array

arr1.ndim # 1
arr2.ndim # 2
arr3.ndim # 3

# .dtype # get data type of array if we change only one element in array to float the whole array becomes float

arr1.dtype # int64
arr2.dtype # int64
arr3.dtype # int64

# .size # get number of elements in array

arr1.size # 3
arr2.size # 6
arr3.size # 12



12

In [8]:
type(arr1) # <class 'numpy.ndarray'>
type(arr2) # <class 'numpy.ndarray'>
type(arr3) # <class 'numpy.ndarray'>

numpy.ndarray

In [9]:
import pandas as pd

df2 = pd.DataFrame(arr2) # it never work on 3D array
df2
df1 = pd.DataFrame(arr1)
df1 

,0
0,1
1,2
2,3


Creating Numpy Arrays

In [10]:
# Creating Numpy arrays

arr = np.array([1,2,3])
arr

# Array has all elements one's

arr_1 = np.ones((2,3))
arr_1

# Aaray has all elements zero's

arr0 = np.zeros((2,3))
arr0

# Array has all elements random

arr_range = np.arange(0,11,2) # start, stop, step
arr_range

arr_linspace = np.linspace(0,10,5) # start, stop, number of elements
arr_linspace

# Manual range

arr_random = np.random.randint(0,11,size = (2,3)) # start, stop, size
arr_random

# Auto range

array = np.random.rand(2,3) # 0 to 1 random numbers in 2 rows and 3 columns
array

array([[0.05844508, 0.27625723, 0.94649028],
       [0.81989309, 0.27966666, 0.51484178]])

Testing Something


In [11]:
# arr = np.array([[1,2,3],[4,6]])
# arr

# ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# As we know,
# if we convert one element in list into float the whole list becomes float.


arr = np.array([[1,2,3],[4,5.0,6]])
arr.dtype

# Now
# if I convert one element to string or other data type then what's happen ?

arr = np.array([[1,2,3],[4,'5',6]])
arr.dtype # <U21 -> Unicode string with maximum length of 21 characters
arr


array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

Random Seed

In [12]:
# Seed

np.random.seed(seed = 0)

rand_matrix = np.random.rand(2,3)
rand_matrix.sum()

np.float64(3.481198341773846)

Accessing Elements

In [13]:
arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [14]:
arr[0][0][0]
# same as
arr[0,0,0]

np.int64(1)

In [15]:
# genrate random 2 3D arrays

import numpy as np

arr_random = np.random.randint(10, size=(2,3,3,3))
arr_random

# Now
# Access it's first row

arr_random[0,0,0]


array([4, 7, 6])

Manipulation

In [16]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a3 = np.array([[[1,2,6,3],[4,9,5,6]],[[1,2,7,3],[4,5,6,7]]])
a3

array([[[1, 2, 6, 3],
        [4, 9, 5, 6]],

       [[1, 2, 7, 3],
        [4, 5, 6, 7]]])

In [18]:
# we cann't add two diffrent order of matrixs like

# a2*a3 # it causes broad casting (value error) error

a2*a3[:2,:2,:3]


array([[[ 1,  4, 18],
        [16, 45, 30]],

       [[ 1,  4, 21],
        [16, 25, 36]]])

Aggregrations

In [19]:
a1 = [1,2,3]
sum(a1) # this is python method : slower
# same as
np.sum(a1) # this is numpy method : faster

np.int64(6)

In [20]:
long_arr = np.random.random(1000)
long_arr.size
long_arr

%timeit sum(long_arr) # Python sum

%timeit np.sum(long_arr) # Numpy sum



1.49 ms ± 610 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


111 μs ± 11.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
# mean 

np.mean(long_arr)

# std = standard deviation 

np.std(long_arr)
#  same as
np.sqrt(np.var(long_arr))


# variance

np.var(long_arr)



np.float64(0.08241436292407496)

Matrix Multiplication

Dot Product Vs Element wise multiplication

In [22]:
# Element wise multiplication

np.random.seed(0)

arr1 = np.random.randint(10,size = (3,3))
arr2 = np.random.randint(10,size = (3,3))
arr1*arr2


array([[20,  0, 18],
       [24, 56,  9],
       [18, 35, 14]])

In [23]:
# Dot product

# columns = rows
np.random.seed(0)

matrix1 = np.random.randint(10,size = (3,4))
matrix2 = np.random.randint(10,size = (3,4))

matrix1.dot(matrix2.T) 

# we need to transpose matrix2 to make it compatible
# for dot product


array([[ 61,  62,  76],
       [161, 141, 185],
       [ 91, 104, 156]])

Reshape and Transpose

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

Sorting Arrays

In [42]:
np.random.seed(0)
array = np.random.randint(10, size=(3, 5))
array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [45]:
np.sort(array,axis = 0) # by default axis = 1 which means row wise sorting

array([[5, 0, 3, 2, 1],
       [7, 3, 5, 3, 4],
       [9, 6, 8, 8, 7]])

In [48]:
np.argsort(array,axis = 0) # by default axis = 1 which means row wise sorting

array([[0, 0, 0, 1, 2],
       [2, 1, 1, 0, 1],
       [1, 2, 2, 2, 0]])

In [ ]:
np.argmin(array,axis = 0) # by default it returns a min value from a matrix but if we add axis = 0 or 1 it gives the min value index from a matrix

array([0, 0, 0, 1, 2])

In [ ]:
np.argmax(array,axis = 0) # by default it returns a max value from a matrix but if we add axis = 0 or 1 it gives the max value index from a matrix

array([1, 2, 2, 2, 0])

Reading Images

remaining code of numpy from colab google